name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    steps:
    - uses: actions/checkout@v2
      with:
        fetch-depth: 0

    - name: Installing Node.js
      uses: actions/setup-node@v1
      with:
        node-version: 12.x

    - name: Installing dependencies
      run: yarn

    - name: Checking Tests
      run: yarn test

    - name: Checking commit message
      uses: wagoid/commitlint-github-action@v1

    - name: Checking linting
      run: yarn lint
